name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/sleepfake/
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install uv
        run: |
          pip install --upgrade uv

      - name: Install dependencies
        run: |
          uv sync --no-dev

      - name: Build
        run: |
          uv build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          attestations: true
