# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install Rye
      run: |
        curl -sSf https://rye-up.com/get | RYE_INSTALL_OPTION="--yes" bash
    - name: Install dependencies
      run: |
        rye sync
    - name: Lint
      run: |
        rye lint
        rye run mypy
    - name: Test with pytest
      run: |
        rye run test
